#!/bin/sh

airport_path="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"

if air_info=($(eval "$airport_path" -I | grep -E "^ *(agrCtlRSSI|state|SSID):" | awk '{print $2}')) ; then

  rssi=${air_info[0]}
  state=${air_info[1]}
  ssid=${air_info[2]}

  case "$state" in
    "running" )
      #signals=(▁ ▂ ▄ ▆ █)
      signal=""
      rssi_=$(expr 5 - ${rssi} / -20)

      case $rssi_ in
        0)signal="*";;
        1)signal="●○○○○";;
        2)signal="●●○○○";;
        3)signal="●●●○○";;
        4)signal="●●●●○";;
        5)signal="●●●●●";;
      esac

      ssid_shortform=$(echo $ssid | head -c 7)
      airport_=" ${signal} #[underscore]${ssid_shortform}#[default] "
    ;;
    "init"    ) airport_="#[fg=yellow]  #[fg=default]" ;;
    *         ) airport_="#[fg=red]   #[fg=default]" ;;
  esac  
  echo "|#[default]${airport_}|#[default] "
fi
