#!/bin/sh



if battery_info=$(/usr/bin/pmset -g ps | awk '{ if (NR == 2) print $3 " " $4 }' | sed -e "s/;//g" -e "s/%//") ; then
  battery_quantity=$(echo $battery_info | awk '{print $1}')
  if [[ ! $battery_info =~ "discharging" ]]; then
    battery="#[bold]#[fg=colour11]⚡︎$battery_quantity%#[default]"
  elif (( $battery_quantity < 11 )); then
    battery="#[fg=colour1]$battery_quantity%#[default]"
  else
    battery="#[fg=colour2]$battery_quantity%#[default]"
  fi
else
  battery="#[bg=colour27,fg=white] No battery"
fi
  echo $battery
